name: "Build Code Components"
run-name: "Build Code from ${{ github.ref }}"

on:
  workflow_dispatch:

jobs:
  build_api:
    uses: zingdevlimited/actions-helpers/.github/workflows/build-twilio-functions.yaml@v4
    with:
      SERVICE_DIRECTORY: workspaces/api
      BUILD_COMMAND: "yarn build:shared && yarn build:api"
      INCLUDE_VERSION_ASSET: true
