name: "Deploy Solution"
run-name: |
  Deploy Solution to ${{ inputs.ENVIRONMENT }}
   ${{ inputs.TWILIO_FUNCTIONS && '[API]' || '' }}
   ${{ inputs.FLEX_PLUGIN && '[Flex Plugin]' || '' }}

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        description: Environment
        options:
          - Develop
          - UAT
          - Production
      TWILIO_FUNCTIONS:
        type: boolean
        description: Twilio Functions
      FLEX_PLUGIN:
        type: boolean
        description: Flex Plugin

permissions:
  contents: read
  actions: read

env:
  FUNCTIONS_SERVICE_NAME: RepoName-api
  TWILIO_ACCOUNT_SID: ${{ vars[format('{0}_TWILIO_ACCOUNT_SID', inputs.ENVIRONMENT)] }}
  TWILIO_API_KEY: ${{ vars[format('{0}_TWILIO_API_KEY', inputs.ENVIRONMENT)] }}
  TWILIO_API_SECRET: ${{ secrets[format('{0}_TWILIO_API_SECRET', inputs.ENVIRONMENT)] }}

jobs:
  deploy_twilio_functions:
    if: inputs.TWILIO_FUNCTIONS == true
    uses: zingdevlimited/actions-helpers/.github/workflows/deploy-twilio-functions.yaml@v4
    with:
      SERVICE_DIRECTORY: workspaces/api
      BUILD_WORKFLOW_NAME: build-code.yaml
      TWILIO_ACCOUNT_SID: ${{ vars[format('{0}_TWILIO_ACCOUNT_SID', inputs.ENVIRONMENT)] }}
      TWILIO_API_KEY: ${{ vars[format('{0}_TWILIO_API_KEY', inputs.ENVIRONMENT)] }}
    secrets:
      TWILIO_API_SECRET: ${{ secrets[format('{0}_TWILIO_API_SECRET', inputs.ENVIRONMENT)] }}

  deploy_flex_plugin:
    if: inputs.FLEX_PLUGIN == true
    uses: zingdevlimited/actions-helpers/.github/workflows/deploy-twilio-flex-plugin.yaml@v4
    with:
      PLUGIN_DIRECTORY: workspaces/plugin
      BUILD_WORKFLOW_NAME: build-code.yaml
      ALLOW_VERSION_OVERWRITE: true
      TWILIO_ACCOUNT_SID: ${{ vars[format('{0}_TWILIO_ACCOUNT_SID', inputs.ENVIRONMENT)] }}
      TWILIO_API_KEY: ${{ vars[format('{0}_TWILIO_API_KEY', inputs.ENVIRONMENT)] }}
    secrets:
      TWILIO_API_SECRET: ${{ secrets[format('{0}_TWILIO_API_SECRET', inputs.ENVIRONMENT)] }}
  
  release_flex_plugin:
    if: inputs.FLEX_PLUGIN == true
    needs: deploy_flex_plugin
    uses: zingdevlimited/actions-helpers/.github/workflows/release-twilio-flex-plugin-list.yaml@v4
    with:
      RELEASE_NAME: "Autorelease Plugin ${{ needs.deploy_flex_plugin.outputs.PLUGIN_NAME }}@${{ needs.deploy_flex_plugin.outputs.PLUGIN_VERSION }}"
      RELEASE_DESCRIPTION: "Released from ${{ github.repository }}. (${{ github.workflow }} Run ${{ github.run_number }})"
      PLUGIN_VERSIONS: |
        ${{ needs.deploy_flex_plugin.outputs.PLUGIN_NAME }}=${{ needs.deploy_flex_plugin.outputs.PLUGIN_VERSION }}
      TWILIO_API_KEY: ${{ vars[format('{0}_TWILIO_API_KEY', inputs.ENVIRONMENT)] }}
    secrets:
      TWILIO_API_SECRET: ${{ secrets[format('{0}_TWILIO_API_SECRET', inputs.ENVIRONMENT)] }}
  
  configure_twilio:
    needs:
      - deploy_twilio_functions
      - deploy_flex_plugin
    if: |
      !failure() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-24.04
    steps:
      - name: Get Functions Service
        id: functionsService
        uses: zingdevlimited/actions-helpers/get-twilio-functions-service@v4
        with:
          SERVICE_NAME: ${{ env.FUNCTIONS_SERVICE_NAME }}
          TWILIO_API_KEY: ${{ env.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ env.TWILIO_API_SECRET }}

      - name: Update Function Variables
        id: updateFunctionVariables
        uses: zingdevlimited/actions-helpers/update-twilio-functions-variables@v4
        with:
          SERVICE_NAME: ${{ env.FUNCTIONS_SERVICE_NAME }}
          TWILIO_API_KEY: ${{ env.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ env.TWILIO_API_SECRET }}
          VARIABLES_ENV: | # Add Twilio Functions Variables here
            CORS_ORIGIN=${{ inputs.ENVIRONMENT == 'develop' && '*' || 'flex.twilio.com' }}

      - name: Update RepoName Flex Configuration Section
        id: updatePluginConfig
        uses: zingdevlimited/actions-helpers/update-flex-config@v4
        with:
          TWILIO_ACCOUNT_SID: ${{ env.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ env.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ env.TWILIO_API_SECRET }}
          CONFIG_SECTION: "RepoNameConfig"
          CONFIG_DATA_JSON: | # Add Twilio Flex Config here
            {
              "FLEX_APP_API_BASE_URL": "${{ steps.functionsService.outputs.BASE_URL }}"
            }
