name: "Deploy Solution"
run-name: |
  Deploy Solution to ${{ inputs.ENVIRONMENT }}
   ${{ inputs.TWILIO_FUNCTIONS && '[API]' || '' }}

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        description: Environment
        options:
          - Develop
          - UAT
          - Production
      TWILIO_FUNCTIONS:
        type: boolean
        description: Twilio Functions

permissions:
  contents: read
  actions: read

env:
  FUNCTIONS_SERVICE_NAME: RepoName-api
  TWILIO_ACCOUNT_SID: ${{ vars[format('{0}_TWILIO_ACCOUNT_SID', inputs.ENVIRONMENT)] }}
  TWILIO_API_KEY: ${{ vars[format('{0}_TWILIO_API_KEY', inputs.ENVIRONMENT)] }}
  TWILIO_API_SECRET: ${{ secrets[format('{0}_TWILIO_API_SECRET', inputs.ENVIRONMENT)] }}

jobs:
  deploy_twilio_functions:
    if: inputs.TWILIO_FUNCTIONS == true
    uses: zingdevlimited/actions-helpers/.github/workflows/deploy-twilio-functions.yaml@v4
    with:
      SERVICE_DIRECTORY: workspaces/api
      BUILD_WORKFLOW_NAME: build-code.yaml
      TWILIO_ACCOUNT_SID: ${{ vars[format('{0}_TWILIO_ACCOUNT_SID', inputs.ENVIRONMENT)] }}
      TWILIO_API_KEY: ${{ vars[format('{0}_TWILIO_API_KEY', inputs.ENVIRONMENT)] }}
    secrets:
      TWILIO_API_SECRET: ${{ secrets[format('{0}_TWILIO_API_SECRET', inputs.ENVIRONMENT)] }}
  
  configure_twilio:
    needs:
      - deploy_twilio_functions
    if: |
      !failure() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-24.04
    steps:
      - name: Get Functions Service
        id: functionsService
        uses: zingdevlimited/actions-helpers/get-twilio-functions-service@v4
        with:
          SERVICE_NAME: ${{ env.FUNCTIONS_SERVICE_NAME }}
          TWILIO_API_KEY: ${{ env.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ env.TWILIO_API_SECRET }}

      - name: Update Function Variables
        id: updateFunctionVariables
        uses: zingdevlimited/actions-helpers/update-twilio-functions-variables@v4
        with:
          SERVICE_NAME: ${{ env.FUNCTIONS_SERVICE_NAME }}
          TWILIO_API_KEY: ${{ env.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ env.TWILIO_API_SECRET }}
          VARIABLES_ENV: | # Add Twilio Functions Variables here
            CORS_ORIGIN=${{ inputs.ENVIRONMENT == 'develop' && '*' || 'flex.twilio.com' }}
            SPOTIFY_CLIENT_ID=${{ vars[format('{0}_SPOTIFY_CLIENT_ID', inputs.ENVIRONMENT)] }}
            SPOTIFY_CLIENT_SECRET=${{ secrets[format('{0}_SPOTIFY_CLIENT_SECRET', inputs.ENVIRONMENT)] }}
            SPOTIFY_REDIRECT_URI=${{ vars[format('{0}_SPOTIFY_REDIRECT_URI', inputs.ENVIRONMENT)] }}
            SPOTIFY_REFRESH_TOKEN=${{ vars[format('{0}_SPOTIFY_REFRESH_TOKEN', inputs.ENVIRONMENT)] }}
            SPOTIFY_SOURCE_PLAYLIST_ID=${{ vars[format('{0}_SPOTIFY_SOURCE_PLAYLIST_ID', inputs.ENVIRONMENT)] }}
            SPOTIFY_DESTINATION_PLAYLIST_ID=${{ vars[format('{0}_SPOTIFY_DESTINATION_PLAYLIST_ID', inputs.ENVIRONMENT)] }}
            SPOTIFY_LOOKBACK_MINUTES=${{ vars[format('{0}_SPOTIFY_LOOKBACK_MINUTES', inputs.ENVIRONMENT)] }}
