name: "[PR] Test RepoName Plugin"

on:
  pull_request:
    branches:
    - develop
    paths:
    - workspaces/plugin/**
  workflow_dispatch:

jobs:

  test: 
    uses: zingdevlimited/actions-helpers/.github/workflows/test-twilio-flex-plugin.yaml@v4
    with: 
      PLUGIN_DIRECTORY: workspaces/plugin
      TEST_COMMAND: yarn lint:plugin && yarn build:shared && yarn build:plugin && yarn test:plugin